version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./domain.com.conf:/etc/nginx/conf.d/domain.com.conf
  simple-web:
    image: yeasy/simple-web:latest
